export const EVENTDATA = [
  {
    date: 'Fri, Nov 11 2022',
    time: '5:00',
    title: 'Cambodia Tech Expo 2022',
    location: 'phnom-penh',
    img: '/event_poster3.jpg',
    datetime: {
      hasCustomTime: false,
      startDate: '2023-01-04',
      endDate: '2023-01-04',
      endTime: '13:22',
      startTime: '13:22',
    },
    id: 0,
  },
  {
    date: 'Sat, Nov 26 2022',
    time: '9:00',
    title: 'Business Development',
    location: 'phnom-penh',
    img: '/event_poster1.jpg',
    id: 1,
  },
  {
    date: 'Sat, Nov 26 2022',
    time: '9:00',
    title: 'Business Development',
    location: 'phnom-penh',
    img: '/event_poster1.jpg',
    id: 10,
  },
  {
    date: 'Sat, Nov 26 2022',
    time: '13:00',
    title: "Making Smart Investment: A Beginner's Guide",
    location: 'phnom-penh',
    img: '/event_poster7.webp',
    id: 2,
  },
  {
    date: 'Sat, Nov 12 2022',
    time: '8:00',
    title: 'Open Career Fair 2022 Hospitality / Tourism',
    location: 'phnom-penh',
    img: '/event_poster5.jpg',
    id: 3,
  },
  {
    date: 'Thu, Nov 17 2022',
    time: '17:00',
    title: 'Deep Learning and Khmer Text Recognition: Solution...',
    location: 'phnom-penh',
    img: '/event_poster2.jpg',
    id: 4,
  },
  {
    date: 'Sun, Dec 11 2023',
    time: '9:00',
    title: 'Nadri Korean Festival',
    location: 'phnom-penh',
    img: '/event_poster4.jpg',
    id: 5,
  },
];
