export const EVENTDATA = [
  {
    date: 'Fri, Nov 11 - Sun, Nov 13',
    time: '5:00 PM',
    title: 'Cambodia Tech Expo 2022',
    location: 'Phnom Penh',
    img: '/event_poster3.jpg',
    id: 0,
  },
  {
    date: 'Sat, Nov 26',
    time: '9:00 AM',
    title: 'Business Development',
    location: 'Phnom Penh',
    img: '/event_poster1.jpg',
    id: 1,
  },
  {
    date: 'Sat, Nov 26',
    time: '1:00 PM',
    title: "Making Smart Investment: A Beginner's Guide",
    location: 'Phnom Penh',
    img: '/event_poster7.webp',
    id: 2,
  },
  {
    date: 'Sat, Nov 12',
    time: '8:00 AM',
    title: 'Open Career Fair 2022 Hospitality / Tourism',
    location: 'Phnom Penh',
    img: '/event_poster5.jpg',
    id: 3,
  },
  {
    date: 'Thu, Nov 17',
    time: '5:00 PM',
    title: 'Deep Learning and Khmer Text Recognition: Solution...',
    location: 'Phnom Penh',
    img: '/event_poster2.jpg',
    id: 4,
  },
  {
    date: 'Sun, Dec 11 - Mon, Dec 12',
    time: '9:00 AM',
    title: 'Nadri Korean Festival',
    location: 'Phnom Penh',
    img: '/event_poster4.jpg',
    id: 5,
  },
];
